### ISSUE TITLE
HF Nozzle Parameter Request

### ISSUE THREAD

**Issue by beegmouse** [prusa3d/PrusaSlicer-settings-prusa-fff#2]
Upgrading an XL with a high flow nozzle doesn't affect print times, even with the new HF printer profiles.

I believe Prusaslicer is respecting the maximum volumetric flow (MVS) set in the filament profiles.

I'm requesting a new HFMVS field in the filament database. HF printer profiles could use that value to limit MVS over the standard one. to start with you can safely make new HFMVS = MVS x 1.25 for an instant boost, and tune individual profiles more accurately over time.

**Comment by rtyr** [comment]
Actually most of the filaments have its separate version with HF volumetric limit. So there is no need for separate parameter. Some filament profiles are shared between HF and non-HF intentionally (for example fibre filled).
