### ISSUE TITLE
PERF: Quick/Simple PrusaSlicer Fix to surface quality issue experienced with 'Colorfabb Steelfill' profile

### ISSUE THREAD

**Issue by tobymould** [prusa3d/PrusaSlicer-settings-prusa-fff#3]
## Is your feature request related to a problem? Please describe.
Using the default prusaslicer profile for this material, all samples had poor surface quality due to overextrusion. 

- **Printer** - Prusa MK4S (stock)
- **Nozzle** - E3D Obxidian 0.4mm High Flow
- **Material** - ColorFabb SteelFill (ordered from Prusa website)
- **PrusaSlicer Profile** - "ColorFabb steelFill @MK4S"
- **Layer Height** - 0.25mm Structural
- **Print Sheet** - Textured (if this is somehow relevent)

**Default 'Extrusion Multiplier' is presently 1.15x** on this profile but my battery of 4 repeat tests showed this to consistently be too high for all samples I printed with it. The surface quality produced was consistently poor.

- 1.15x (default) - poor topfill surface quality.
- 1.1x - poor topfill surface quality but a little less than 1.15x
- **1.05x - best balanced compromise** - good topfill surface quality while still visible perimeter wall interbonding.
- 1.00x - best topfill surface quality but some evidence of potential underextrusion between 'perimeter' path walls.

## Describe the solution you'd like
I would like for you to test the topfill surface quality of prints using the default slicer profile above, and repeat them again but with my improvement suggestion of reducing the 'Extrusion multiplier'. 

Update 'Extrusion Multiplier' for the above mentioned profile down to ~1.05x (or something in this area) as the best results I found were around 1.05x, as described above.

## Describe how it would work
N/A - see above

## Describe alternatives you've considered
N/A - there are no alternatives immediately obvious to me except this.

## Additional context
unable to attach prusaslicer file as not supported on github.

**Photograph:**

**- Blue = Default setting of 1.15x**
**- Orange = 1x multiplier sample**

Will add better photos in next 24 hours when lighting conditions become favourable for a clear photo of samples

![IMG_0595](https://github.com/user-attachments/assets/b87817a9-d043-4437-a36f-3b4c708c0507)

**Comment by tobymould** [comment]
> Increased flow was intentional for inrease the reliability with 0.4mm nozzle (larger nozzle diameters have lower multiplier). With this particular filament, it is expected that objects will be post-processed (sanded and polished for metal look), so some level of overextrusion is usually fine. But we may revisit this with the latest batch of this filament.

Yeah, that makes sense - figured I'd share anyway just incase

**Comment by rtyr** [comment]
It's decreased a little bit now.
